### ISSUE TITLE
Problem retrieving interologs

### ISSUE THREAD

**Issue by pabloech** [PPiMapBuilder/PPiMapBuilder#25]
Let's take the example of the protein AARSD1, if as starting point we query the human version (Q9BTE6), no interactions retrieved. If we start with the mouse version (Q3THG9) 2 interactions retrieved. It seems that if it doesn't find an interactor in the query organism then it stops searching, while interactors in other organisms are still valid as interolgs, even though when they're the only ones found.

**Comment by gcornut** [comment]
I encountered this kind of behavior on other protein also. I will look at it and solve this problem for version 0.9.

**Comment by gcornut** [comment]
Bug fixed in version 0.9 that will be published very shortly (in the current week).

**Comment by pabloech** [comment]
I tried again with 0.9 version and still the same problem, with Q9BTE6, no interactions retrieved, with the mouse version Q3THG9 now just 1 interaction retrieved

**Comment by gcornut** [comment]
That's very strange. On my computer I get the expected result. I tested multiple queries with your proteins and got this results:

Selected databases: DIP, MINT, IntAct

| Query | Result |
| --- | --- |
| Protein: Q9BTE6 <br> Reference organism : Human <br> Other organism : Mouse | ![image](https://cloud.githubusercontent.com/assets/939567/3361461/e83febc6-fafe-11e3-9a3d-5d5053b638f2.png) |
| Protein: Q9BTE6 <br> Reference organism : Mouse <br> Other organism : Human | ![image](https://cloud.githubusercontent.com/assets/939567/3361490/3c0fe5d0-faff-11e3-9f73-a1af3313b73f.png) |
| Protein: Q3THG9 <br> Reference organism : Human <br> Other organism : Mouse | ![image](https://cloud.githubusercontent.com/assets/939567/3361594/35241e0c-fb00-11e3-8678-140097be75a5.png) |
| Protein: Q3THG9 <br> Reference organism : Mouse <br> Other organism : Human | ![image](https://cloud.githubusercontent.com/assets/939567/3361597/3f6e2830-fb00-11e3-86fd-425ca20c92ec.png) |

Maybe you could try to uninstall and reinstall PPiMapBuilder to see if it works better.
